### ISSUE TITLE
As a developer, I’d like to have a component for scheduling ads that billboard will show based on the available info.

### ISSUE THREAD

**Issue by berkayyildiz97** [lorem-bitsinartiksum/view-magnet#12]
**AdScheduler:** Scheduler for ads based on the available object & environment info.
Things to watch out for:
- Watch out for priorities.
- All ads must be displayed at least N seconds. N must be configurable by env variables.

**Comment by cakir-enes** [comment]
Related:
- [ ] #13 
- [ ] #14
