### ISSUE TITLE
As a user, I would like to have a UI for view and query my ad metrics (show time etc)

### ISSUE THREAD

**Issue by cakir-enes** [lorem-bitsinartiksum/view-magnet#5]
__Metric Service UI:__ UI viewing metrics.

**Comment by alper-oner** [comment]
There should be a page that allows viewing a metrics(show time, environmental information etc).

![resim](https://user-images.githubusercontent.com/36198409/72824816-f4e2a600-3c86-11ea-96df-4aca0bff225c.png)

**Comment by bur-k** [comment]
f48f1d32efe6b17419338d19afe4262c3fbeb6b4
