### ISSUE TITLE
As a user, I would like to have a Web page to add/delete/update ads and view company ads metrics.

### ISSUE THREAD

**Issue by cakir-enes** [lorem-bitsinartiksum/view-magnet#8]
__Web Application - Frontend:__ Landing page for product and ad manager for customers.
Things to watch out for:
- UI should be intuitive to use.

**Comment by bur-k** [comment]
Customer login and register pages
![Untitled2](https://user-images.githubusercontent.com/36450327/72823944-8a7d3600-3c85-11ea-8bf0-0f244c51356d.jpg)
Advertisement upload page and an example of advertisement
![Untitled](https://user-images.githubusercontent.com/36450327/72823848-615ca580-3c85-11ea-9e79-747150f21d9c.jpg)

**Comment by bur-k** [comment]
a9bd3dfb65890471ab7f3dbb6ef178262b7033c3
